### ISSUE TITLE
Do not remove original cause of the exception

### ISSUE THREAD

**Issue by lancedfr** [XeroAPI/Xero-Java#223]
**SDK you're using (please complete the following information):**
 - Version 4.1.2

**Is your feature request related to a problem? Please describe.**
When we instantiate a new exception (in XeroApiExceptionHandler#execute method), we should always set the caught exception as its cause. Otherwise, we lose the message and stack trace that describe the exception event that caused the exception. 

**Describe the solution you'd like**
The exception class and all its subclasses should provide a constructor method which accepts the original exception as a parameter and set it as the cause.

**Additional context**
it is very difficult to determine the root cause of the exceptions. Especially when the XeroApiExceptionHandler#execute method reaches the else block where all details of the exception are lost.

```
} else {
 throw new XeroApiException(statusCode, e.getStatusMessage());
}
```

Perhaps [this blog post](https://stackify.com/common-mistakes-handling-java-exception/) has a better example at "mistake 5"

I think this feature request should have status In Discussion for other input. I'm happy to implement this change if approved.

**Comment by lancedfr** [comment]
Hi @SidneyAllen I'm happy to implement this change. It is dependant on #221 so that will need to be resolved first.

This change in short will impact all Exception classes. As well as AccountingApi, AssetApi, BankFeedsApi, PayrollAuApi and PayrollUkApi - more specifically where the API classes call XeroApiExceptionHandler will need to pass the exception cause.

I have the change ready to go. I can create a PR for you to review further if you like?

**Comment by SidneyAllen** [comment]
@lancedfr - this change will require a bit more coordination.  The following classes are generated AccountingApi, AssetApi, BankFeedsApi, PayrollAuApi and PayrollUkApi - so we can't take a PR for them.  

If you include an example of the change for AccountingApi (if it's the same for all API methods) in the comments of your PR, I can make the change to our java templates for generating.  In the PR, you CAN make changes to the exception classes which are not generated.

**Comment by SidneyAllen** [comment]
@lancedfr - was this resolved in PR #224 ?

**Comment by lancedfr** [comment]
> @lancedfr - was this resolved in PR #224 ?

Hi @SidneyAllen - Thanks for the follow up. I've been busy moving house but managed to find some time to implement the above in this PR https://github.com/XeroAPI/Xero-Java/pull/231.

To answer your question, this was not resolved in https://github.com/XeroAPI/Xero-Java/pull/224.

I've left an explanation in the PR description. Let me know if you need any details.

**Comment by SidneyAllen** [comment]
PR #231 merged and adjusted to include NZ payroll
